import { icons } from '../components/Layout';

export const adminNav = [
  { to: '/admin', labelKey: 'nav.admin.home', icon: icons.dashboard, end: true },
  { to: '/admin/subeler', labelKey: 'nav.admin.branches', icon: icons.room },
  { to: '/admin/tara', labelKey: 'nav.admin.scan', icon: icons.scan },
  { to: '/admin/kitaplar', labelKey: 'nav.admin.books', icon: icons.books },
  { to: '/admin/satin-alma', labelKey: 'nav.admin.purchase', icon: icons.loan },
  { to: '/admin/bagis', labelKey: 'nav.admin.donations', icon: icons.books },
  { to: '/admin/kitap-yorumlari', labelKey: 'nav.admin.reviews', icon: icons.books },
  { to: '/admin/dijital-kaynaklar', labelKey: 'nav.admin.digital', icon: icons.books },
  { to: '/admin/tez-arsivi', labelKey: 'nav.admin.thesis', icon: icons.report },
  { to: '/admin/kopyalar', labelKey: 'nav.admin.copies', icon: icons.shelf },
  { to: '/admin/envanter', labelKey: 'nav.admin.inventory', icon: icons.scan },
  { to: '/admin/uyeler', labelKey: 'nav.admin.members', icon: icons.users },
  { to: '/admin/personel', labelKey: 'nav.admin.staff', icon: icons.users },
  { to: '/admin/odunc', labelKey: 'nav.admin.loans', icon: icons.loan },
  { to: '/admin/transferler', labelKey: 'nav.admin.transfers', icon: icons.loan },
  { to: '/admin/rezervasyonlar', labelKey: 'nav.admin.reservations', icon: icons.room },
  { to: '/admin/etkinlikler', labelKey: 'nav.admin.events', icon: icons.report },
  { to: '/admin/kulupler', labelKey: 'nav.admin.clubs', icon: icons.club },
  { to: '/admin/cezalar', labelKey: 'nav.admin.penalties', icon: icons.penalty },
  { to: '/admin/duyurular', labelKey: 'nav.admin.announcements', icon: icons.bell },
  { to: '/admin/hasar-kayip', labelKey: 'nav.admin.damage', icon: icons.shelf },
  { to: '/admin/raporlar', labelKey: 'nav.admin.reports', icon: icons.report },
  { to: '/admin/rapor-aktar', labelKey: 'nav.admin.reportExport', icon: icons.report },
  { to: '/admin/denetim', labelKey: 'nav.admin.audit', icon: icons.report },
  { to: '/guvenlik', labelKey: 'nav.admin.security', icon: icons.penalty },
];
