/**
 * Sistem kuralları — tüm iş mantığı buradan yönetilir
 */
module.exports = {
  MAX_LOANS_PER_MEMBER: 3,
  LOAN_DAYS: 14,
  PENALTY_PER_DAY_TL: 5,
  LOST_BOOK_PENALTY_TL: 250,
  DAMAGED_BOOK_PENALTY_TL: 100,
  LIGHT_DAMAGE_PENALTY_TL: 25,
  COVER_DAMAGE_PENALTY_TL: 50,
  MISSING_PAGE_PENALTY_TL: 75,
  RESERVATION_VIOLATION_TL: 25,
  ROOM_NOSHOW_PENALTY_TL: 20,
  DUE_SOON_DAYS: 3,
  RESERVATION_PICKUP_HOURS: 24,
  MAX_LOAN_EXTENSIONS: 2,
  EXTENSION_DAYS: 7,
};
