/** Çalışma odaları — öğrenci rezervasyonu için */
const STUDY_TIME_SLOTS = [
  { baslangic: '08:00', bitis: '10:00', label: '08:00 – 10:00' },
  { baslangic: '10:00', bitis: '12:00', label: '10:00 – 12:00' },
  { baslangic: '12:00', bitis: '14:00', label: '12:00 – 14:00' },
  { baslangic: '14:00', bitis: '16:00', label: '14:00 – 16:00' },
  { baslangic: '16:00', bitis: '18:00', label: '16:00 – 18:00' },
  { baslangic: '18:00', bitis: '20:00', label: '18:00 – 20:00' },
];

const STUDY_ROOMS = [
  {
    id: 'merkez-sessiz-a',
    ad: 'Merkez Sessiz Çalışma A',
    kat: '1. Kat',
    sube: 'Merkez Kütüphane',
    kapasite: 8,
    akilli_tahta: false,
    bilgisayar: false,
    sessiz_oda: true,
    grup_odasi: false,
    aciklama: 'Bireysel sessiz çalışma masaları',
  },
  {
    id: 'merkez-grup-alpha',
    ad: 'Merkez Grup Odası Alpha',
    kat: '2. Kat',
    sube: 'Merkez Kütüphane',
    kapasite: 6,
    akilli_tahta: true,
    bilgisayar: false,
    sessiz_oda: false,
    grup_odasi: true,
    aciklama: '4–6 kişilik grup çalışması, akıllı tahta',
  },
  {
    id: 'merkez-dijital',
    ad: 'Dijital Çalışma Laboratuvarı',
    kat: '3. Kat',
    sube: 'Merkez Kütüphane',
    kapasite: 12,
    akilli_tahta: true,
    bilgisayar: true,
    sessiz_oda: true,
    grup_odasi: false,
    aciklama: 'Bilgisayarlı bireysel çalışma istasyonları',
  },
  {
    id: 'muh-proje',
    ad: 'Mühendislik Proje Odası',
    kat: 'Zemin',
    sube: 'Mühendislik Fakültesi Kütüphanesi',
    kapasite: 10,
    akilli_tahta: true,
    bilgisayar: true,
    sessiz_oda: false,
    grup_odasi: true,
    aciklama: 'Proje ve ekip çalışması için donanımlı oda',
  },
  {
    id: 'muh-sessiz',
    ad: 'Mühendislik Sessiz Köşe',
    kat: '1. Kat',
    sube: 'Mühendislik Fakültesi Kütüphanesi',
    kapasite: 4,
    akilli_tahta: false,
    bilgisayar: false,
    sessiz_oda: true,
    grup_odasi: false,
    aciklama: 'Tek kişilik sessiz çalışma kabinleri',
  },
  {
    id: 'sag-grup-1',
    ad: 'Sağlık Grup Çalışma 1',
    kat: '1. Kat',
    sube: 'Sağlık Bilimleri Kütüphanesi',
    kapasite: 8,
    akilli_tahta: true,
    bilgisayar: false,
    sessiz_oda: false,
    grup_odasi: true,
    aciklama: 'Vaka tartışması ve grup ders çalışması',
  },
  {
    id: 'sag-sessiz',
    ad: 'Sağlık Sessiz Araştırma',
    kat: '2. Kat',
    sube: 'Sağlık Bilimleri Kütüphanesi',
    kapasite: 6,
    akilli_tahta: false,
    bilgisayar: false,
    sessiz_oda: true,
    grup_odasi: false,
    aciklama: 'Sessiz bireysel okuma ve not alma',
  },
  {
    id: 'hukuk-arastirma',
    ad: 'Hukuk Araştırma Salonu',
    kat: '1. Kat',
    sube: 'Hukuk Kütüphanesi',
    kapasite: 12,
    akilli_tahta: false,
    bilgisayar: false,
    sessiz_oda: true,
    grup_odasi: false,
    aciklama: 'Hukuk kaynaklarına yakın sessiz çalışma',
  },
  {
    id: 'hukuk-grup',
    ad: 'Hukuk Grup & Moot Odası',
    kat: '2. Kat',
    sube: 'Hukuk Kütüphanesi',
    kapasite: 14,
    akilli_tahta: true,
    bilgisayar: true,
    sessiz_oda: false,
    grup_odasi: true,
    aciklama: 'Moot court hazırlığı ve grup seminerleri',
  },
  {
    id: 'merkez-seminer',
    ad: 'Merkez Seminer Odası',
    kat: '4. Kat',
    sube: 'Merkez Kütüphane',
    kapasite: 20,
    akilli_tahta: true,
    bilgisayar: true,
    sessiz_oda: false,
    grup_odasi: true,
    aciklama: 'Büyük grup sunumları ve çalıştaylar',
  },
];

function getStudyRoomById(id) {
  return STUDY_ROOMS.find((r) => r.id === id) || null;
}

function getAllStudyRooms() {
  return STUDY_ROOMS;
}

module.exports = {
  STUDY_ROOMS,
  STUDY_TIME_SLOTS,
  getStudyRoomById,
  getAllStudyRooms,
};
